# Generated by Django 6.0.6 on 2026-07-06 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
