# Generated by Django 6.0.6 on 2026-07-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail4',
            field=models.URLField(blank=True, null=True),
        ),
    ]
